// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $(document.body).mousewheel(function(e) {
      var $container;
      $container = $("#container");
      $container.scrollTop($container.scrollTop() + (50 / -e.deltaY));
      return console.log(e.deltaX, e.deltaY, e.deltaFactor, $container.scrollTop(), $container.scrollTop() + (50 / -e.deltaY));
    });
    return $("a").each(function(idx, link) {
      return $(link).click(function() {
        console.log(link.href);
        return false;
      });
    });
  });

}).call(this);
