// Generated by CoffeeScript 1.7.1
(function() {
  var handle_anchors, handle_anchors2, scrollTo, titleize;

  titleize = function(str) {
    return str.replace(/\w\S*/g, function(txt) {
      return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
    });
  };

  handle_anchors = function() {
    var hash;
    $("a").click(function() {
      var $toElement, hash, toPosition;
      console.log("ouch", this.hash);
      if (this.hash) {
        hash = this.hash.substr(1);
        $toElement = $("[id=" + hash + "]");
        toPosition = $toElement.position().top;
        console.log("sdfkljasdfsdjafkljs", toPosition);
        $("#container").animate({
          scrollTop: toPosition
        }, 2000, "easeOutBounce");
      }
      return false;
    });
    if (location.hash) {
      hash = location.hash;
      window.scroll(0, 0);
      return $("a[href=" + hash + "]").click();
    }
  };

  scrollTo = function(section, pushState) {
    var toY;
    toY = section.offsetTop;
    $("#container").animate({
      scrollTop: toY
    }, 2000, "easeOutBounce");
    if (pushState) {
      return history.pushState({
        section: section.id
      }, titleize(section.id), section.id);
    }
  };

  handle_anchors2 = function() {
    var $section;
    if (location.pathname.length > 1) {
      $section = $("[id=" + (location.pathname.substring(1)) + "]");
      if ($section.length > 0) {
        scrollTo($section[0]);
      }
    }
    $("a").click(function() {
      var section;
      section = this.getAttribute("href");
      $section = $("[id=" + section + "]");
      if ($section.length > 0) {
        scrollTo($section[0], true);
      }
      return false;
    });
    return $(window).on("popstate", function() {
      if (location.pathname.length > 1) {
        $section = $("[id=" + (location.pathname.substring(1)) + "]");
        if ($section.length > 0) {
          return scrollTo($section[0], false);
        }
      } else {
        return $("#container").animate({
          scrollTop: 0
        }, 2000, "easeOutBounce");
      }
    });
  };

  $(function() {
    history.replaceState({
      section: "splash-container"
    }, "splash", "");
    console.log(titleize("hello friend"));
    $(document.body).mousewheel(function(e) {
      var $container, current_scroll, farthest;
      $container = $("#container");
      current_scroll = $container.scrollTop();
      $container.scrollTop(current_scroll + (50 / -e.deltaY));
      current_scroll = $container.scrollTop();
      farthest = "";
      $(".row").each(function() {
        if (current_scroll >= this.offsetTop - 100) {
          farthest = this;
        }
        return console.log(current_scroll, this.offsetTop, this.id, farthest.id);
      });
      if (history.state.section !== farthest.id) {
        if (farthest.id === $(".row")[0].id) {
          history.pushState({
            section: farthest.id
          }, "", "/");
        } else {
          history.pushState({
            section: farthest.id
          }, titleize(farthest.id), farthest.id);
        }
        return console.log("You made it to " + farthest.id + "!");
      }
    });
    return handle_anchors2();
  });

}).call(this);
