# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adam Keenan
email: adam.g.keenan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Budding web developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adam-keenan.com" # the base hostname & protocol for your site
twitter_username: adamk33n3r
github_username:  adamk33n3r

# Build settings
#highlighter: pygments
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "main"
      author: "Adam Keenan"
gems:
  - jekyll-coffeescript
